# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’

    
target 'XYProject' do
    
# ignore all warnings from all pods
inhibit_all_warnings!
    
pod 'iCarousel', '1.8.2'
pod 'DACircularProgress', '2.3.1'
    
    
pod 'AFNetworking', '3.1.0'


end


